package com.hss01248.media.mymediastore.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hss01248.media.mymediastore.bean.BaseMediaInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASE_MEDIA_INFO".
*/
public class BaseMediaInfoDao extends AbstractDao<BaseMediaInfo, String> {

    public static final String TABLENAME = "BASE_MEDIA_INFO";

    /**
     * Properties of entity BaseMediaInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FolderPathOrUri = new Property(0, String.class, "folderPathOrUri", false, "FOLDER_PATH_OR_URI");
        public final static Property SmbHost = new Property(1, String.class, "smbHost", false, "SMB_HOST");
        public final static Property SmbRootDir = new Property(2, String.class, "smbRootDir", false, "SMB_ROOT_DIR");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property IsHiden = new Property(4, int.class, "isHiden", false, "IS_HIDEN");
        public final static Property PathOrUri = new Property(5, String.class, "pathOrUri", true, "PATH_OR_URI");
        public final static Property FileSize = new Property(6, long.class, "fileSize", false, "FILE_SIZE");
        public final static Property UpdatedTime = new Property(7, long.class, "updatedTime", false, "UPDATED_TIME");
        public final static Property MaxSide = new Property(8, int.class, "maxSide", false, "MAX_SIDE");
        public final static Property Duration = new Property(9, int.class, "duration", false, "DURATION");
        public final static Property Path = new Property(10, String.class, "path", false, "PATH");
        public final static Property Type = new Property(11, int.class, "type", false, "TYPE");
    }


    public BaseMediaInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BaseMediaInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASE_MEDIA_INFO\" (" + //
                "\"FOLDER_PATH_OR_URI\" TEXT," + // 0: folderPathOrUri
                "\"SMB_HOST\" TEXT," + // 1: smbHost
                "\"SMB_ROOT_DIR\" TEXT," + // 2: smbRootDir
                "\"NAME\" TEXT," + // 3: name
                "\"IS_HIDEN\" INTEGER NOT NULL ," + // 4: isHiden
                "\"PATH_OR_URI\" TEXT PRIMARY KEY NOT NULL ," + // 5: pathOrUri
                "\"FILE_SIZE\" INTEGER NOT NULL ," + // 6: fileSize
                "\"UPDATED_TIME\" INTEGER NOT NULL ," + // 7: updatedTime
                "\"MAX_SIDE\" INTEGER NOT NULL ," + // 8: maxSide
                "\"DURATION\" INTEGER NOT NULL ," + // 9: duration
                "\"PATH\" TEXT," + // 10: path
                "\"TYPE\" INTEGER NOT NULL );"); // 11: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASE_MEDIA_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BaseMediaInfo entity) {
        stmt.clearBindings();
 
        String folderPathOrUri = entity.getFolderPathOrUri();
        if (folderPathOrUri != null) {
            stmt.bindString(1, folderPathOrUri);
        }
 
        String smbHost = entity.getSmbHost();
        if (smbHost != null) {
            stmt.bindString(2, smbHost);
        }
 
        String smbRootDir = entity.getSmbRootDir();
        if (smbRootDir != null) {
            stmt.bindString(3, smbRootDir);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getIsHiden());
 
        String pathOrUri = entity.getPathOrUri();
        if (pathOrUri != null) {
            stmt.bindString(6, pathOrUri);
        }
        stmt.bindLong(7, entity.getFileSize());
        stmt.bindLong(8, entity.getUpdatedTime());
        stmt.bindLong(9, entity.getMaxSide());
        stmt.bindLong(10, entity.getDuration());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(11, path);
        }
        stmt.bindLong(12, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BaseMediaInfo entity) {
        stmt.clearBindings();
 
        String folderPathOrUri = entity.getFolderPathOrUri();
        if (folderPathOrUri != null) {
            stmt.bindString(1, folderPathOrUri);
        }
 
        String smbHost = entity.getSmbHost();
        if (smbHost != null) {
            stmt.bindString(2, smbHost);
        }
 
        String smbRootDir = entity.getSmbRootDir();
        if (smbRootDir != null) {
            stmt.bindString(3, smbRootDir);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getIsHiden());
 
        String pathOrUri = entity.getPathOrUri();
        if (pathOrUri != null) {
            stmt.bindString(6, pathOrUri);
        }
        stmt.bindLong(7, entity.getFileSize());
        stmt.bindLong(8, entity.getUpdatedTime());
        stmt.bindLong(9, entity.getMaxSide());
        stmt.bindLong(10, entity.getDuration());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(11, path);
        }
        stmt.bindLong(12, entity.getType());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5);
    }    

    @Override
    public BaseMediaInfo readEntity(Cursor cursor, int offset) {
        BaseMediaInfo entity = new BaseMediaInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // folderPathOrUri
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // smbHost
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // smbRootDir
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getInt(offset + 4), // isHiden
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // pathOrUri
            cursor.getLong(offset + 6), // fileSize
            cursor.getLong(offset + 7), // updatedTime
            cursor.getInt(offset + 8), // maxSide
            cursor.getInt(offset + 9), // duration
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // path
            cursor.getInt(offset + 11) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BaseMediaInfo entity, int offset) {
        entity.setFolderPathOrUri(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSmbHost(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSmbRootDir(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsHiden(cursor.getInt(offset + 4));
        entity.setPathOrUri(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFileSize(cursor.getLong(offset + 6));
        entity.setUpdatedTime(cursor.getLong(offset + 7));
        entity.setMaxSide(cursor.getInt(offset + 8));
        entity.setDuration(cursor.getInt(offset + 9));
        entity.setPath(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setType(cursor.getInt(offset + 11));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BaseMediaInfo entity, long rowId) {
        return entity.getPathOrUri();
    }
    
    @Override
    public String getKey(BaseMediaInfo entity) {
        if(entity != null) {
            return entity.getPathOrUri();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BaseMediaInfo entity) {
        return entity.getPathOrUri() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
