package com.hss01248.media.mymediastore.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hss01248.media.mymediastore.bean.BaseMediaFolderInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASE_MEDIA_FOLDER_INFO".
*/
public class BaseMediaFolderInfoDao extends AbstractDao<BaseMediaFolderInfo, String> {

    public static final String TABLENAME = "BASE_MEDIA_FOLDER_INFO";

    /**
     * Properties of entity BaseMediaFolderInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property Cover = new Property(1, String.class, "cover", false, "COVER");
        public final static Property PathOrUri = new Property(2, String.class, "pathOrUri", false, "PATH_OR_URI");
        public final static Property SmbHost = new Property(3, String.class, "smbHost", false, "SMB_HOST");
        public final static Property SmbRootDir = new Property(4, String.class, "smbRootDir", false, "SMB_ROOT_DIR");
        public final static Property Id = new Property(5, String.class, "id", true, "ID");
        public final static Property DiskType = new Property(6, int.class, "diskType", false, "DISK_TYPE");
        public final static Property Count = new Property(7, int.class, "count", false, "COUNT");
        public final static Property FileSize = new Property(8, long.class, "fileSize", false, "FILE_SIZE");
        public final static Property Hidden = new Property(9, int.class, "hidden", false, "HIDDEN");
        public final static Property UpdatedTime = new Property(10, long.class, "updatedTime", false, "UPDATED_TIME");
        public final static Property Duration = new Property(11, long.class, "duration", false, "DURATION");
        public final static Property Order = new Property(12, int.class, "order", false, "ORDER");
        public final static Property MediaType = new Property(13, int.class, "mediaType", false, "MEDIA_TYPE");
    }


    public BaseMediaFolderInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BaseMediaFolderInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASE_MEDIA_FOLDER_INFO\" (" + //
                "\"NAME\" TEXT," + // 0: name
                "\"COVER\" TEXT," + // 1: cover
                "\"PATH_OR_URI\" TEXT," + // 2: pathOrUri
                "\"SMB_HOST\" TEXT," + // 3: smbHost
                "\"SMB_ROOT_DIR\" TEXT," + // 4: smbRootDir
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 5: id
                "\"DISK_TYPE\" INTEGER NOT NULL ," + // 6: diskType
                "\"COUNT\" INTEGER NOT NULL ," + // 7: count
                "\"FILE_SIZE\" INTEGER NOT NULL ," + // 8: fileSize
                "\"HIDDEN\" INTEGER NOT NULL ," + // 9: hidden
                "\"UPDATED_TIME\" INTEGER NOT NULL ," + // 10: updatedTime
                "\"DURATION\" INTEGER NOT NULL ," + // 11: duration
                "\"ORDER\" INTEGER NOT NULL ," + // 12: order
                "\"MEDIA_TYPE\" INTEGER NOT NULL );"); // 13: mediaType
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASE_MEDIA_FOLDER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BaseMediaFolderInfo entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String cover = entity.getCover();
        if (cover != null) {
            stmt.bindString(2, cover);
        }
 
        String pathOrUri = entity.getPathOrUri();
        if (pathOrUri != null) {
            stmt.bindString(3, pathOrUri);
        }
 
        String smbHost = entity.getSmbHost();
        if (smbHost != null) {
            stmt.bindString(4, smbHost);
        }
 
        String smbRootDir = entity.getSmbRootDir();
        if (smbRootDir != null) {
            stmt.bindString(5, smbRootDir);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(6, id);
        }
        stmt.bindLong(7, entity.getDiskType());
        stmt.bindLong(8, entity.getCount());
        stmt.bindLong(9, entity.getFileSize());
        stmt.bindLong(10, entity.getHidden());
        stmt.bindLong(11, entity.getUpdatedTime());
        stmt.bindLong(12, entity.getDuration());
        stmt.bindLong(13, entity.getOrder());
        stmt.bindLong(14, entity.getMediaType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BaseMediaFolderInfo entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String cover = entity.getCover();
        if (cover != null) {
            stmt.bindString(2, cover);
        }
 
        String pathOrUri = entity.getPathOrUri();
        if (pathOrUri != null) {
            stmt.bindString(3, pathOrUri);
        }
 
        String smbHost = entity.getSmbHost();
        if (smbHost != null) {
            stmt.bindString(4, smbHost);
        }
 
        String smbRootDir = entity.getSmbRootDir();
        if (smbRootDir != null) {
            stmt.bindString(5, smbRootDir);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(6, id);
        }
        stmt.bindLong(7, entity.getDiskType());
        stmt.bindLong(8, entity.getCount());
        stmt.bindLong(9, entity.getFileSize());
        stmt.bindLong(10, entity.getHidden());
        stmt.bindLong(11, entity.getUpdatedTime());
        stmt.bindLong(12, entity.getDuration());
        stmt.bindLong(13, entity.getOrder());
        stmt.bindLong(14, entity.getMediaType());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5);
    }    

    @Override
    public BaseMediaFolderInfo readEntity(Cursor cursor, int offset) {
        BaseMediaFolderInfo entity = new BaseMediaFolderInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cover
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pathOrUri
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // smbHost
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // smbRootDir
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // id
            cursor.getInt(offset + 6), // diskType
            cursor.getInt(offset + 7), // count
            cursor.getLong(offset + 8), // fileSize
            cursor.getInt(offset + 9), // hidden
            cursor.getLong(offset + 10), // updatedTime
            cursor.getLong(offset + 11), // duration
            cursor.getInt(offset + 12), // order
            cursor.getInt(offset + 13) // mediaType
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BaseMediaFolderInfo entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCover(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPathOrUri(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSmbHost(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSmbRootDir(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDiskType(cursor.getInt(offset + 6));
        entity.setCount(cursor.getInt(offset + 7));
        entity.setFileSize(cursor.getLong(offset + 8));
        entity.setHidden(cursor.getInt(offset + 9));
        entity.setUpdatedTime(cursor.getLong(offset + 10));
        entity.setDuration(cursor.getLong(offset + 11));
        entity.setOrder(cursor.getInt(offset + 12));
        entity.setMediaType(cursor.getInt(offset + 13));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BaseMediaFolderInfo entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(BaseMediaFolderInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BaseMediaFolderInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
